name: Deploy to AWS S3
description: Deploy a static website via AWS S3
inputs:
  bucket:
    description: "S3 Bucket Name"
    required: true
  bucket-region:
    description: "region of the S3 bucket"
    required: false
    default: "ap-south-1"
  dist-folder:
    description: "folder containing the deployable files"
    required: true
runs:
  using: 'node20'
  main: test.js