name: Deploy Project
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Load & cache Dependencies
        uses: ./.github/actions/cached-deps
      - name: Run tests
        id: run-tests
        continue-on-error: true
        run: npm test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file-name: ${{ steps.js-filename.outputs.file-name }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Load & cache Dependencies
        uses: ./.github/actions/cached-deps
      - name: Build website
        run: npm run build
      - name: Publish JS file name
        id: js-filename
        run: find dist/assets -name "*.js" -type f -execdir echo "file-name={}" >> $GITHUB_OUTPUT ";"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json

  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: dist-files
    secrets: inherit
  #    secrets:
  #      some-secret: ${{ secrets.SOME_SECRET }}

  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: print deploy output
        run: echo "${{ needs.deploy.outputs.result }}"

  report:
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"