name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact file
        required: true
        type: string
        default: dist
    outputs:
      result:
        description: result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    secrets:
      SOME_SECRET:
        required: true
#    secrets:
#      some-secret:
#        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List contents
        run: ls
      - name: Echo Secret
        run: echo "${{ secrets.SOME_SECRET }}"
      - name: Output information
        run: |
          echo "Deploying & uploading ..."
          echo "${{ toJSON(github) }}"
      - name: set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
          
